version: '3'
services:
  redisdoc:
    container_name: redisdoc
    image: redis
    ports:
    - "6379:6379"
    networks:
    - production
    volumes:
    - /data/redis:/data
  mysqldoc:
    container_name: mysqldoc
    build:
      context: .
      dockerfile: ./mysql.dockerfile
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: document
    networks:
    - production
    volumes:
      - /data/database:/var/lib/mysql
  springboot:
    container_name: springboot
    build:
      context: .
      dockerfile: ./main/springboot.dockerfile
    image: springboot
    ports:
      - "8080:8080"
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
    - production
    depends_on:
      - mysqldoc
      - redisdoc
networks:
  production:
    driver: bridge