spring:
  datasource:
#    url: jdbc:mysql://mysqldoc:3306/document
#    username: springuser
#    password: password
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
    timeout: 10000
  cache:
    redis:
      use-key-prefix: true
    type: redis

application:
  validation-api:
#    url: http://validation:8081/session
    url: http://localhost:8081/session

mobicare:
  jwt:
    secret: $2a$12$ykaSFLXZ2NUCSyNsYu4eae8obBxTMFEl9UMVHwxvsk.0J31NyS7p6