spring:
  datasource:
#    url: jdbc:mysql://mysqldoc:3306/document
#    username: springuser
#    password: password
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
    timeout: 10000
  cache:
    redis:
      use-key-prefix: true
    type: redis

application:
  validation-api:
#    url: http://validation:8081/session
    url: http://localhost:8081/session

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka