server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  application:
    name: 'jwt'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka