spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cache:
    redis:
      use-key-prefix: true
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka