spring:
  application:
    name: 'main'
  datasource:
    Driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  redis:
    host: 'localhost'
    timeout: 10000

