spring:
  application:
    name: 'main'
    bucket:
      name: sysdoc-devschool
  datasource:
    Driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  redis:
    host: 'redis'
    timeout: 10000
  flyway:
    url: jdbc:mysql://localhost:32779/document
    user: root
    password: password

cloud:
  aws:
    credentials:
      access-key: AKIAZN7XOX3WPAWKJSKB
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false