spring:
  datasource:
    Driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldoc:3306/document
    username: springuser
    password: password
  redis:
    host: 'redis'
    timeout: 10000
  cache:
    redis:
      use-key-prefix: true
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka