spring:
  application:
    name: 'main'
    bucket:
      name: sysdoc-devschool
  datasource:
    Driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32779/document
    username: root
    password: password
  redis:
    host: 'redis'
    timeout: 10000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION} 
    stack:
      auto: false
